### ISSUE TITLE
wpn_g43

### ISSUE THREAD

**Issue by valentynkp** [Redotix/3DSS-for-GAMMA#3]
![Fatal Error](https://github.com/user-attachments/assets/fb031585-be80-4ece-9e04-cbd89f06f6e2)

Game show me this error, when I get the weapon

**Comment by andtheherois** [comment]
you need the reanimation file for it. its slated to be added to gamma as a standard mod but for the time being you have to add it to your own game

**Comment by valentynkp** [comment]
Thanks
