### ISSUE TITLE
Reticle size problem

### ISSUE THREAD

**Issue by valentynkp** [Redotix/3DSS-for-GAMMA#4]
In the 1.18 update I have a problem with the sights, I don't have shaders inside the sight, I guess it's because of the update and the reticle size of the sights.
![1 17 -2](https://github.com/user-attachments/assets/1361119c-26bc-48e8-a761-1db6ffddc1dc)
![1 17](https://github.com/user-attachments/assets/79b7c582-de24-480d-841a-a349fc67c057)
![1 18 -2](https://github.com/user-attachments/assets/21e33872-f802-4aff-b5da-e32431b141d9)
![1 18](https://github.com/user-attachments/assets/0f1463a9-2325-4840-b59d-47aff9111698)

**Comment by andtheherois** [comment]
already adjusted

**Comment by valentynkp** [comment]
Thanks you
