### ISSUE TITLE
Schmidt and Bender PM II 3-12-50 scope - shader not working

### ISSUE THREAD

**Issue by valentynkp** [Redotix/3DSS-for-GAMMA#5]
![G28](https://github.com/user-attachments/assets/a7ef0efc-163d-431c-8ab4-9eee4a2666a3)

On Remington 700 AICS, Remington 700 McMillan and G28 shader not working on version 2.3 and 2.5, on 1.17 it is still working.

**Comment by andtheherois** [comment]
check pin in main thread

**Comment by valentynkp** [comment]
![List mods](https://github.com/user-attachments/assets/10ce95ff-e1b7-4a12-a07f-da097983b1e2)
![Scope](https://github.com/user-attachments/assets/b609b75d-d412-41c5-aa7e-7bf0312fb819)
It still the same in version 2.9 on updated GAMMA.

**Comment by andtheherois** [comment]
Because it's not part of the main mod...
