### ISSUE TITLE
Schmidt and Bender PM II 3-12-50 scope - shader not working v2.9

### ISSUE THREAD

**Issue by valentynkp** [Redotix/3DSS-for-GAMMA#7]
![List mods](https://github.com/user-attachments/assets/10ce95ff-e1b7-4a12-a07f-da097983b1e2)
![Scope](https://github.com/user-attachments/assets/b609b75d-d412-41c5-aa7e-7bf0312fb819)
It still the same in version 2.9 on updated GAMMA.

_Originally posted by @valentynkp in https://github.com/Redotix/3DSS-for-GAMMA/issues/5#issuecomment-2392843976_

**Comment by valentynkp** [comment]
![List mods](https://github.com/user-attachments/assets/6b1d7322-3f62-4659-b3b3-a256b69d7249)

**Comment by andtheherois** [comment]
This has to do with bas22, not the main mod. I'm very aware these scopes have been broken. They'll be fixed soon. If I close a problem there's no need to reopen it.

**Comment by valentynkp** [comment]
I think I fix it, it works if I overwrite it with v1.17 like that, 
![Fix](https://github.com/user-attachments/assets/3c6fc725-11f8-482b-bf1f-56e663f3c68e)
Sure it is not the correct way, but if it works, it works
